{% set name = "sim-tools" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sim_tools-{{ version }}.tar.gz
  sha256: 32363e5de61d65c0f6a70fe4e53ad81592f00f64ce1015d767670e6572484b3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - matplotlib-base >=3.1.3
    - numpy >=1.18.1
    - pandas >=2.0.0
    - scikit-learn >=1.0.0
    - scipy >=1.4.1

test:
  imports:
    - sim_tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://tommonks.github.io/sim-tools
  summary: Simulation Tools for Education and Practice
  dev_url: https://github.com/TomMonks/sim-tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TomMonks
