{% set python_min = "3.10" %}
{% set name = "sim-tools" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sim_tools-{{ version }}.tar.gz
  sha256: 8ef84a04500487e0c8314e6392edbb95c988cd201133a0d8f1f99cab9c69e75a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.1.3
    - numpy >=1.18.1
    - pandas >=2.0.0
    - rich >=13.7.1
    - scikit-learn >=1.0.0
    - plotly >=6.0.0

test:
  imports:
    - sim_tools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://tommonks.github.io/sim-tools
  summary: Simulation Tools for Education and Practice
  dev_url: https://github.com/TomMonks/sim-tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TomMonks
